### PR TITLE
Added react-ga to support google analytics 

### PR DESCRIPTION
**Pull request by ShimiSun**
Setting up the platform to support google analytics.
Adding Analytics function and leveraging existing Router Component to pass the path and child to be used for google analytics.
Tested it with debug messages of react-ga and the Google Analytics visualizations.
Screen Shot 2019-10-29 at 4 28 52 PM

This PR is resolving the issues from https://github.com/grommet/grommet-designer/pull/35

### CODE REVIEW

**Review by ericsoderberghp — DISMISSED** [review]

**Comment by ericsoderberghp** [comment]
grommet-designer doesn't use a Router itself because it doesn't have any routes for itself. The history pushState location is driven by whatever design screen paths are created. So, analytics over the paths aren't really interesting, and don't correlate.

Instead, I think we should instrument analytics for how often a component is added (AddComponent.js), deleted, or duplicated (Properties.js), how often a design is created (reset() in Designs.js), loaded locally (select() in Designs.js), imported (load() in Designs.js), or published design referenced (line 35 in App.js), how often a design is published, downloaded, or converted to code (Share.js).

**Comment by ShimiSun** [comment]
I think the metrics you suggested are interesting and we should aim at collecting this data.
Regardless, I think that with the existing router monitoring, we can still benefit from understanding how long users are using the app, and where they are coming from to use the designer. 
I don't think this information is tracked unless we have the current suggested behavior of this PR.

**Comment by ericsoderberghp** [comment]
We don't want `pageview` though, as that doesn't mean anything for grommet-designer. This would be sufficient, without adding `<Analytics />` or `<Router />` as a component:
```
import ReactGA from 'react-ga';
ReactGA.initialize('UA-000000-01');
ReactGA.pageview(window.location.pathname + window.location.search);
```

**Comment by ShimiSun** [comment]
I'll be closing this PR due to PR #40

**Pull request closed without merging**
